### ISSUE TITLE
face crop

### ISSUE THREAD

**Issue by Fly2flies** [jerryli27/TwinGAN#23]
Hi,
  Thank you for sharing such a fun project！But, I'm sorry that it doesn't work well when I use my images(they're all Asian) and your pretrained model.I guess whether because I didn't put the face right in the center of the image.
  Is that right?
  Thanks a lot.

**Comment by jerryli27** [comment]
Hi,
Is it an open sourced dataset? A lot of things can go wrong during training and not having faces in the center can make it harder for the generator to learn.

However my model should be somewhat robust against faces not cropped to the center. In fact I intentionally crop the face images during training so that they are not always at the center. (Which works slightly better in the real world dataset when I use a webcam for demo). So if your face dataset are somewhat clean (no faces turning completely sideways), it should work fine.
